### ISSUE TITLE
Read from TCP socket should be non-blocking

### ISSUE THREAD

**Issue by jean553** [jean553/rust-chat-server#17]

**Comment by allan-simon** [comment]
I think it's solved now ?

**Comment by jean553** [comment]
Yes, it's solved and I close the issue. We fixed it because we moved the TCP socket writting process into a different thread for every single client, though I am still interested to know if we can read using a non-blocking function. Do you think it's possible ?

**Comment by allan-simon** [comment]
it is, but then it's a change of paradigm in the way your server is architectured
